### ISSUE TITLE
About control interface

### ISSUE THREAD

**Issue by uenian33** [norkator/nx100-remote-control#15]
It would be nice to have the controller written like ROS style, here is one example:

moveL.go(arm_joints, wait=True)
#moveL.stop()

which MoveL is the commander class, and one arg "wait" indicating if the program should wait untill the movement is done.

**Comment by norkator** [comment]
@uenian33 see https://github.com/norkator/nx100-remote-control/pull/16 if thats something you needed?

**Comment by uenian33** [comment]
> @uenian33 see #16 if thats something you needed?

yes, it fits very well!
