### ISSUE TITLE
Configuration of the NX100 controller

### ISSUE THREAD

**Issue by guess1000** [norkator/nx100-remote-control#21]
Great work! 

Please add detailed explanation of the configuration of the NX100 controller, how to configure on witch Lan port, and so on. If you can, please add some pictures 

Thanks!

**Comment by norkator** [comment]
> Great work!
> 
> Please add detailed explanation of the configuration of the NX100 controller, how to configure on witch Lan port, and so on. If you can, please add some pictures
> 
> Thanks!

Lets start with mandatory part first. Do you know your NX100 Yaskawa master password.. I cannot publicly tell it myself because don't want to get into trouble. You need that password to do changes.

**Comment by norkator** [comment]
I try add details today later when getting closer to robot. I don't remember all at the moment.

**Comment by norkator** [comment]
Added some instructions which should help.
